---
apiVersion: v1
kind: Deploymemt
metadata:
  name: nop-commerce
spec:
  minReadySeconds: 5
  replicas: 2
  selector: 
    app: nop-commerce
  strategy: 
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25
      maxUnavailable: 25
  template:
    metadata:
      app: nop-commerce
    spec:
      containers: 
        - name: nop-commerce
          image: jalasuresh/nop-commerce1.0
          ports:
            - containerPort: 80
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: svc-nop
spec:
  type: LoadBalancer
  selector:
    app: nop-commerce
  ports:
      - targetPort: 80
        port: 35000
        protocol: TCP
