---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nop-commerce
spec:
  minReadySeconds: 5
  replicas: 2
  selector: 
    matchLabels:
      app: nopcommerce
  strategy: 
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25
      maxUnavailable: 25
  template:
    metadata:
      labels:
        app: nopcommerce
    spec:
      containers: 
        - name: nop-commerce
          image: jalasuresh/nopcommerce:1.0
          ports:
            - containerPort: 80
              name: nop-svc
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: svc-nop
spec:
  type: LoadBalancer
  selector:
    app: nop-commerce
  ports:
    - name: webport
      port: 35000
      targetPort: 80
      protocol: TCP 

---
apiVersion: v1
kind: Pod
metadata:
  name: my-sql-db
spec:
  containers:
    - name: mysql-contianer
      image: mysql:8-debian
      ports:
        - containerPort: 3306
          protocol: TCP
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: rootroot
        - name: MYSQL_DATABASE
          value: employees
        - name: MYSQL_USER
          value: suresh
        - name: MYSQL_PASSWORD
          value: suresh
      volumeMounts:
        - mountPath: /var/lib/mysql
          name: mysql-vol
  volumes:
      - name: mysql-vol
        emptyDir:     

---
apiVersion: v1
kind: Service
metadata: 
  name: svc-db
spec:
  type: ClusterIP
  selector:
    app: nop-commerce
  ports:
      - targetPort: 3306
        port: 3306
        protocol: TCP