---
apiVersion: v1
kind: Deploymemt
metadata:
  name: nop-commerce
spec:
  minReadySeconds: 5
  replicas: 2
  selector: 
    app: nop-commerce
    name: my-sql-db
  strategy: 
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25
      maxUnavailable: 25
  template:
    metadata:
      app: nop-commerce
    spec:
      containers: 
        - name: nop-commerce
          image: jalasuresh/nopcommerce1.0
          ports:
            - containerPort: 80
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: svc-nop
spec:
  type: LoadBalancer
  selector:
    app: nop-commerce
  ports:
      - targetPort: 80
        port: 35000
        protocol: TCP
---
apiVersion: v1
kind: Pod
metadata:
  name: my-sql-db
spec:
  containers:
    - name: mysql-contianer
      image: mysql:8-debian
      ports:
        - containerPort: 3306
          protocol: TCP
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: rootroot
        - name: MYSQL_DATABASE
          value: employees
        - name: MYSQL_USER
          value: suresh
        - name: MYSQL_PASSWORD
          value: suresh
      volumeMounts:
        - mountPath: /var/lib/mysql
          name: mysql-vol
---
apiVersion: v1
kind: Service
metadata: 
  name: svc-db
spec:
  type: ClusterIP
  selector:
    app: nop-commerce
  ports:
      - targetPort: 3306
        protocol: TCP